Adiciona projetos Android, Kotlin e VBScript
dextra/awesome-dextra pull request #10
Opened 2020-09-11 21:41 UTC by alexandrehtrb

Olá,

Gostaria de contribuir para essa página.

Um dos meus projetos (KotlinMultiplatformExample) é uma prova de conceito simples, mas usei ele em um artigo publicado no blog da Dextra, por isso incluí aqui também.

2020-09-12 00:04 UTC, ohager requested changes
We haven't expressed this explicitely, but let us keep  alphabetical order for new project types . Regarding the proposed projects, it seems that they are merely PoCs than valuable contributions. I might be wrong here. Do/Did you use them in real life projects...or others?

2020-09-12 00:04 UTC, ohager commented on README.md
> + - [Kotlin Multiplatform Example](https://github.com/alexandrehtrb/KotlinMultiplatformExample) - An example of a Kotlin Multiplatform (Kotlin MPP) project for Android and iOS, also using Gradle Kotli
Does this serve as a legit template? Calling it "example" seems more like a Proof-of-Concept, which IMHO should not make it into the list. If it is a real usable project template I recommend to "generalize" it.

2020-09-12 00:04 UTC, ohager commented on README.md
> + - [AssertVBS](https://github.com/alexandrehtrb/AssertVBS) - Testing assertion library for VBScript. Author: [Alexandre Bonfitto](https://github.com/alexandrehtrb/)
Same here. I know, that testing in VBS is PITA - I like the idea... is it a project which can be/was used in real life, or is it "just" a PoC?

2020-09-12 01:22 UTC, alexandrehtrb commented on README.md
> + - [Kotlin Multiplatform Example](https://github.com/alexandrehtrb/KotlinMultiplatformExample) - An example of a Kotlin Multiplatform (Kotlin MPP) project for Android and iOS, also using Gradle Kotli
Acho que é uma prova de conceito simples, talvez seja melhor não incluí-la na lista... removi.

2020-09-12 01:26 UTC, alexandrehtrb commented on README.md
> + - [AssertVBS](https://github.com/alexandrehtrb/AssertVBS) - Testing assertion library for VBScript. Author: [Alexandre Bonfitto](https://github.com/alexandrehtrb/)
Sim, pode ser usado em projetos reais, em testes de integração executados em computadores mais antigos, por exemplo. Pesquisei e encontrei bibliotecas melhores para testes em VBScript no GitHub [(exemplo)](https://github.com/valeriofarias/vbsunit), por isso removi da lista também.

2020-09-12 15:00 UTC, erickzanardo requested changes

2020-09-12 15:00 UTC, erickzanardo commented on README.md
> + - [IridescentView](https://github.com/alexandrehtrb/IridescentView) - Custom ImageView with iridescence effect. Author: [Alexandre Bonfitto](https://github.com/alexandrehtrb/)
Thanks for the contribution, I think this is a valid submission, although It bother me that this is not published on any repository, and the user of the library needs to copy and paste the source file on their project. I think this should be published before this been added here, as said on the CONTRIBUTING.md:

`Published packages/libraries/frameworks (Published meaning people can use this on their own project, using the available publishing method for the platform it is built on)`

If you can publish this and update the README of the project, I am all for on adding this entry to our list.

2020-09-13 00:41 UTC, alexandrehtrb commented on README.md
> + - [IridescentView](https://github.com/alexandrehtrb/IridescentView) - Custom ImageView with iridescence effect. Author: [Alexandre Bonfitto](https://github.com/alexandrehtrb/)
Vou publicar a biblioteca para ser usada, quando estiver publicada eu atualizo aqui :+1:

2020-09-25 18:20 UTC, ohager commented on README.md
> + - [IridescentView](https://github.com/alexandrehtrb/IridescentView) - Custom ImageView with iridescence effect. Author: [Alexandre Bonfitto](https://github.com/alexandrehtrb/)
> Vou publicar a biblioteca para ser usada, quando estiver publicada eu atualizo aqui

any update on this?

2020-09-25 23:45 UTC, alexandrehtrb commented on README.md
> + - [IridescentView](https://github.com/alexandrehtrb/IridescentView) - Custom ImageView with iridescence effect. Author: [Alexandre Bonfitto](https://github.com/alexandrehtrb/)
Pretendo melhorar o código e publicar a biblioteca, mas no momento estou sem tempo; posso fechar o PR, quando estiver pronto eu abro um novo?

2020-09-29 14:48 UTC, ohager commented on README.md
> + - [IridescentView](https://github.com/alexandrehtrb/IridescentView) - Custom ImageView with iridescence effect. Author: [Alexandre Bonfitto](https://github.com/alexandrehtrb/)
makes sense. exited to review the updated version. :rocket:

2021-01-17 00:01 UTC, alexandrehtrb commented on README.md
> + - [IridescentView](https://github.com/alexandrehtrb/IridescentView) - Custom ImageView with iridescence effect. Author: [Alexandre Bonfitto](https://github.com/alexandrehtrb/)
@erickzanardo @ohager , fiz as mudanças necessárias e publiquei a lib em repositórios para outras pessoas usarem (obrigado pelo conselho Erick!)

2021-01-18 12:23 UTC, erickzanardo approved these changes
Excellent!

2021-01-25 12:13 UTC, ohager approved these changes
ok

2021-01-25 12:13 UTC, merged