Add Swift category and my open source project
dextra/awesome-dextra pull request #7
Opened 2020-09-11 18:20 UTC by mugbug

2020-09-11 19:40 UTC, ohager approved these changes
Nice one! Thanks for extending the contributions.md - I need to clarify some details on it.

2020-09-11 23:38 UTC, erickzanardo requested changes
Just fix the order on the index please, otherwise, LGTM

2020-09-11 23:38 UTC, erickzanardo commented on README.md
> + - [Swift](#swift-)
Lets keep this in alphabetic order

2020-09-11 23:39 UTC, ohager commented on README.md
> + - [Swift](#swift-)
Legit!

2020-09-12 00:51 UTC, mugbug commented on README.md
> + - [Swift](#swift-)
Done 👍

2020-09-12 14:52 UTC, erickzanardo approved these changes
LGTM! Thanks for the contribution!

2020-09-12 14:52 UTC, merged