Luca Dillenburg / Add my contribution
dextra/awesome-dextra pull request #9
Opened 2020-09-11 20:15 UTC by LucaDillenburg

Unfortunately, I am leaving Dextra at the end of the month, but I am submitting it because I am a Dextra employee today. However, I completely understand if it doesn't get accepted. :smile:

2020-09-11 23:43 UTC, erickzanardo requested changes
Just need to fix the alphabetical order of the items, otherwise, LGTM

2020-09-11 23:43 UTC, erickzanardo commented on README.md
> + - [GoLang](#golang-)
This list mus follow an alphabetical order

2020-09-11 23:43 UTC, erickzanardo commented on README.md
> + - [Engine-2D-Shooting-Game](https://github.com/lucadillenburg/Engine-2D-Jogo-de-Tiro/) - A top-down 2D shooting game engine. Author: [Luca Dillenburg](github.com/LucaDillenburg)
This list must follow an alphabetical order

2020-09-11 23:43 UTC, erickzanardo commented on README.md
> +<h1>GoLang <img style="margin: 4px 0 0 4px" height="32" src="media/golang.png" alt="GoLang Logo"/></h1>
This list must follow an alphabetical order

2020-09-11 23:52 UTC, ohager reviewed
Interesting projects, but one lacks completeness and the other quality - to sum it up.

2020-09-11 23:52 UTC, ohager commented on README.md
> + - [Open-Computer](https://github.com/Open-Machine/) - A computer built from scratch: from the circuit to the assembler (high-end language coming soon). Author: [Luca Dillenburg](github.com/LucaDille
I looked into the project. The idea is nice, but it's in a very raw state, such I cannot see the representational value for Dextra. Good luck with your project.

2020-09-11 23:52 UTC, ohager commented on README.md
> + - [Engine-2D-Shooting-Game](https://github.com/lucadillenburg/Engine-2D-Jogo-de-Tiro/) - A top-down 2D shooting game engine. Author: [Luca Dillenburg](github.com/LucaDillenburg)
The presentation is good and looks promising. But the projects structure and the code lacks representational quality. Unfortunately, I do not recommend to put this onto the awesome-list. Don't get me wrong: continue studying and doing things you're interested in. That's the way we all evolve! Heads up

2020-09-14 14:11 UTC, LucaDillenburg commented on README.md
> + - [Open-Computer](https://github.com/Open-Machine/) - A computer built from scratch: from the circuit to the assembler (high-end language coming soon). Author: [Luca Dillenburg](github.com/LucaDille
Yes, I agree. Thank you for your feedback! I will be working in it soon!

2020-09-14 14:13 UTC, LucaDillenburg commented on README.md
> + - [Engine-2D-Shooting-Game](https://github.com/lucadillenburg/Engine-2D-Jogo-de-Tiro/) - A top-down 2D shooting game engine. Author: [Luca Dillenburg](github.com/LucaDillenburg)
No problem! I developed this project before studying unit testing and other clean code concepts! Thank you for your feedback anyway!

2020-09-14 14:26 UTC, ohager commented on README.md
> + - [Open-Computer](https://github.com/Open-Machine/) - A computer built from scratch: from the circuit to the assembler (high-end language coming soon). Author: [Luca Dillenburg](github.com/LucaDille
We discussed the Open Machine stuff...as I said before: pretty cool idea, and we all liked it. If you could evolve more on that, such there is kind of working example, we might pull it into the list. 
I read through your README and saw that certain commands are not there (`assembler`), broken link (to circuit folder) and so on. I'm not sure, if you have something functional - if so it seems not to be commited.

2020-09-29 14:51 UTC, ohager commented
@erickzanardo @gustavobigardi I intent to close this PR.  We could pull it to the upcoming "Promising Projects" list, but there is still the situation that @LucaDillenburg left/is leaving Dextra. wdyt?

2020-09-29 18:15 UTC, LucaDillenburg commented
> @erickzanardo @gustavobigardi I intent to close this PR. We could pull it to the upcoming "Promising Projects" list, but there is still the situation that @LucaDillenburg left/is leaving Dextra. wdyt?

Hi Ohager,
I updated the README of the repositories. Now, it only has what has already being developed, no more "TODOs". Everything seems to be working fine. Can you take a look?
Thanks

2021-04-29 20:06 UTC, erickzanardo commented
Not all requested changes were solved (the alphabetical order). Since this PR is a little old I am closing it.

2021-04-29 20:06 UTC, closed without merging